---

- name: Initialize the system
  import_tasks: init.yml

- name: Customize the FHS
  import_tasks: fhs.yml

- name: Initialize the network
  import_tasks: network.yml

- name: Install the snowflake proxy daemon
  import_tasks: snowflake.yml